### ISSUE TITLE
HDF5 File content parse error

### ISSUE THREAD

**Issue by testforvln** [jamesmudd/jhdf#186]
**Describe the bug**
When read 64-bit integer data from a hdf5 file, cannot get the data right.

**To Reproduce**
Steps to reproduce the behaviour:
- I cannot upload the HDF5 file, because github told me that "Something went really wrong, and we can't process that file" when uploading the file.
- The Java code are like below.
`
        String date = "20170103";
        File file = new File("test.h5");

        HdfFile hdfFile = new HdfFile(file);
        DatasetBase dataset = (DatasetBase) hdfFile.getByPath(date);
        IntBuffer buffer = dataset.getDataBuffer().asIntBuffer();
        int data_size = (int) dataset.getSize();

        int[] data = new int[data_size];
        buffer.get(data);
        hdfFile.close();
        System.out.println(Arrays.toString(data));`

**Expected behaviour**
Then first int value of the array "data" is 1237122510, while the actual value is 2017010309250121. The python library h5py can get it right.

**Please complete the following information:**
- `jhdf` version 0.5.6
- Java version jdk1.8.0_171
- OS (Windows, Mac, Linux) Windows

**Additional information**
The software named HDFView 3.0 shows that the data type of the file is "64-bit integer", while Java has 32-bit int and 64-bit long. But using LongBuffer I still cannot get the numbers right. 
How can I share the hdf5 file with you?

**Comment by testforvln** [comment]
After trying some file share websites, I managed to get this link work.
http://www.filedropper.com/test_2503
You can download the h5 file from this link. Hope it helps!

**Comment by jamesmudd** [comment]
The reason is you are accessing the buffer directly (`getDataBuffer`) and incorrectly. Your data can't fit in java `int` and so needs to be placed in a `long`, and as you dataset is 2D a 2D long array `long[][]`. 

`jhdf` seems to be able to read your example file fine, try looking at the https://github.com/jamesmudd/jhdf/blob/master/jhdf/src/main/java/io/jhdf/examples/ReadDataset.java example.

I suggest using `getData()` instead it handles all the type conversion and reshaping for you. You only need to look at accessing the buffer directly if you have some special use case. If you need to index into the array you need to cast to `long[][]` so some code like this will work

```java
try (HdfFile hdfFile = new HdfFile(file)) {
    Dataset dataset = hdfFile.getDatasetByPath("20170103"); // 20170103 is your dataset name
    long[][] data = (long[][]) dataset.getData();
    System.out.println(Arrays.deepToString(data));
}
```
And prints 
```
[[2017010309250121, 2635, 100000, 26350000, 58204, 75914], [2017010309250121, 2635, 1000000, 263500000, 75654, 75914], ...
```
Hope this helps

**Comment by testforvln** [comment]
It really solves my problem. Thanks for your help! Sorry that I had a poor understanding about the buffer and dataset.

**Comment by jamesmudd** [comment]
No problem, good that its working for you. Gives me a few ideas to improve the docs.

**Comment by testforvln** [comment]
I think either a complete introduction for important APIs or a typical user guide is OK. I think you can refer to http://docs.h5py.org/en/stable/, which is the h5py doc site. But it's just a really huge project!
