### ISSUE TITLE
IllegalArgumentException: Argument is not an array for compound attribute

### ISSUE THREAD

**Issue by raedma** [jamesmudd/jhdf#338]
First of all, thanks for all your work.

**Describe the bug**

I try to read a hdf5 file group with a compound scalar attribute but get a `java.lang.IllegalArgumentException` when calling `attribute.getData()`.

**To Reproduce**

Steps to reproduce the behaviour:
- Example file: [test.zip](https://github.com/jamesmudd/jhdf/files/7841510/test.zip)
- Code:

      HdfFile hdf = new HdfFile(PATH);
      Node node = input.getByPath("GROUP");
      Attribute attribute = node.getAttribute("VERSION");
      System.out.println(attribute.getJavaType()); // gives "interface java.util.Map"
      Object data = attribute.getData();

**Expected behaviour**

I'd like the compound attribute data available for further processing.

**Please complete the following information:**
- `jhdf` version: 0.6.4
- Java version: 13
- OS: Windows
- Stack trace if available:

      java.lang.IllegalArgumentException: Argument is not an array
         at java.base/java.lang.reflect.Array.get(Native Method)
         at io.jhdf.dataset.DatasetReader.readDataset(DatasetReader.java:67)
         at io.jhdf.AttributeImpl.getData(AttributeImpl.java:73)

**Comment by jamesmudd** [comment]
Thanks a lot for raising this issue. I have reproduced it using your supplied file. Your right this is a jHDF bug. I have had a really quick look and have a possible fix here #339 but I need to add tests and verify there are not any other cases where this could be wrong. In the meantime if you want to look at, or try the fix would be great to hear if it works for you. If you wanted to add tests and open a PR that would also be great, otherwise I will try to get round to it asap.
